version:
  1.0

#uncomment to specify external flight data
#data:
#  /Users/michael/Desktop/temp/routes.csv

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
